//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPMSForEfashion.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rightssystemEntities : DbContext
    {
        public rightssystemEntities()
            : base("name=rightssystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<module> module { get; set; }
        public DbSet<module_resource> module_resource { get; set; }
        public DbSet<operate> operate { get; set; }
        public DbSet<project> project { get; set; }
        public DbSet<resource> resource { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<role_resource_operate> role_resource_operate { get; set; }
        public DbSet<role_user> role_user { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<department> department { get; set; }
        public DbSet<user_department> user_department { get; set; }
    }
}
