//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPMSForEfashion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string RoleCode { get; set; }
        public string ProjectCode { get; set; }
        public int Sort { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
